service_name            = "optic"
gcp_project_id          = "npm-otp-f6bfc"
region                  = "europe-west1"
zone                    = "europe-west1-b"
private_key_secret_name = "optic-firebase-private-key"
