name: cd

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.gcp_provider_name }}
          service_account: ${{ secrets.gcp_sa }}
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ secrets.GCP_CLOUDRUN_SERVICE_NAME }}
          region: ${{ secrets.GCP_CLOUDRUN_SERVICE_REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          env_vars: >-
              FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }},
              FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
          secrets: |
            FIREBASE_PRIVATE_KEY_BASE64=optic-firebase-private-key:latest
          flags: --allow-unauthenticated --timeout=1800
          source: .
