name: cd-dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  call-deploy-dev:
    uses: ./.github/workflows/deploy-job.yml
    with:
      environment: dev
      grafana_diagnostics_enabled: 'true'
    permissions:
      id-token: write
      contents: read
    secrets:
      gcp_provider_name: ${{ secrets.GCP_PROVIDER_NAME }}
      gcp_sa_email: ${{ secrets.GCP_SA_EMAIL }}
      gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      gcp_cloudrun_service_name: ${{ secrets.GCP_CLOUDRUN_SERVICE_NAME_DEV }}
      gcp_cloudrun_service_region: ${{ secrets.GCP_CLOUDRUN_SERVICE_REGION }}
      firebase_client_email: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      firebase_project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      firebase_private_key_base64: ${{ secrets.FIREBASE_PRIVATE_KEY_BASE64 }}
      firebase_private_key_base64_gcp_secret_name: optic-firebase-private-key-dev
      grafana_otlp_endpoint: ${{ secrets.HUB_GRAFANA_OTLP_ENDPOINT }}
      grafana_instance_id: ${{ secrets.HUB_GRAFANA_INSTANCE_ID }}
      grafana_api_key: ${{ secrets.HUB_GRAFANA_API_KEY }}
      grafana_headers: ${{ secrets.GRAFANA_HEADERS }}
